---
title: "coding & analysis"
output: 
  html_document:
    includes:
      in_header: header.html
    toc: TRUE
    toc_depth: 2
    toc_float: true
---
```{=html}
<style>
h1.title {
    font-family: 'Kanit', sans-serif;
    font-weight: 600;
    font-style: normal;
    font-size: 62px;
    letter-spacing: 8px; 
    text-align:center;
}

h2 {
    font-family: 'Kanit', sans-serif;
    font-weight: 500;
    font-style: normal;
}

h3 {
    font-family: 'Kanit', sans-serif;
    font-weight: 380;
    font-style: normal;
}

.text {
      font-family: 'Roboto', sans-serif;
      font-weight: 400;
      font-size: 24px
      letter-spacing: 1.15px;
      text-align:center;
      }
      
.text2 {
      font-family: 'Roboto', sans-serif;
      font-weight: 400;
      font-size: 24px
      letter-spacing: 1.15px;
      }

.row {
  display: flex;
  flex-wrap: wrap; /* Allows items to wrap */
  justify-content: center; /* Centers items horizontally, adjust as needed */
}

.column {
  flex: 1; /* Adjust this to control how columns grow */
  max-width: 45%; /* Maximum width of each column */
  padding: 5px;
  box-sizing: border-box; /* Includes padding in the element's total width and height */
}
</style>
```

<hr>
R is where it's at. Since being introduced to R and RStudio, they have become essential components of many (if not most) of my computer-based workflows. From geospatial projects and data analysis, to data visualizations and producing documents and reports, R is an incredibly powerful tool. Here are some examples of ways I have used R to conduct my own analysis, provide research support, assist colleagues, and for my own pet projects.
<hr>
<br>

::: {style="text-align: center;"}
## data preprocessing automation
:::

The <a href="https://andrewmcameron.github.io/geospatial.html#urban_gun_crime">urban gun crime work</a> that I did during my time as a member of the City of Newport News GIS team gave me the chance to carry out some interesting spatial analyses and work on developing several apps from the Esri tool kit, including Experience Builder, Dashboard, and Map Viewer (none of which are public-facing, unfortunately). But in order to get to that point, the data generated from the police department's record management query first needed substantial massaging and preparation. 

Because the analyses are expected to be re-run and the dashboard updated on an annual or semi-annual basis to reflect new data, I developed a script to automate the task otherwise laborious task of preprocessing the raw RMS query outputs. I wrote the script as a heavily annoated .Rmd file so that whoever has to interact with it can view it 'visual' mode in RStudio and utilize it effectively with effectively no knowledge of R required. The user needs only to define two variables - a new folder name and the path of the Excel workbook file containing the raw data. The script takes care of the rest. The end result are two CSV files ready to be brought into ArcGIs Pro and geocoded.

You can check out a knitted HTML version of the script that I developed <b><a href="portfolio/Script1_InitialDataProcessing.html" target="blank">by clicking here</a></b>.
<hr>
<br>

::: {style="text-align: center;"}
## modelling algal blooms
:::

<hr>
<br>

::: {style="text-align: center;"}
## visualizing water temperature over time
:::

<hr>
<br>

::: {style="text-align: center;"}
## intro to `osmdata`
:::

<hr>
<br>

::: {style="text-align: center;"}
## bringing fire data to heel
:::

<hr>
<br>
